qemu-system-riscv64     -machine virt     -nographic     -bios ../bootloader/rustsbi-qemu.bin     -device loader,file=target/riscv64gc-unknown-none-elf/release/03priv_inst,addr=0x80200000



cd user/target/riscv64gc-unknown-none-elf/release/
qemu-riscv64 ./00hello_world

qemu-riscv64  target/riscv64gc-unknown-none-elf/release/00hello_world